export const CONFIG = {
    STAR_COUNT: 200,
    STAR_MIN_SIZE: 3,
    STAR_MAX_SIZE: 6,
    OVERLAP_PADDING_BG: 2, 
    MAX_STAR_PLACEMENT_ATTEMPTS: 100,
    MIN_STAR_ALPHA: 0.2,
    MAX_STAR_ALPHA: 1.0,
    LINE_DRAW_SPEED: 0.08
};
